# Site
name: "Qraft Technologies"
title: "Qraft Technologies Tech Blog"
description: "크래프트테크놀로지스의 블로그입니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.jpg'
url: "https://qraftech.github.io"
baseurl: ""
# google_analytics: 'UA-145461596-1'
# disqus: 'demowebsite'
# mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Qraftec:
    name: Qraftec
    display_name: Qraftec
    avatar: 'assets/images/logo.png'
    email: qraftec@qraftec.com
    description: "Artificial Intelligence"    
  권택민:
    name: 권택민
    display_name: 권택민
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: taekmin.kwon@qraftec.com
    description: "Author of Qraftec Dev Blog"
  노승환:
    name: 노승환
    display_name: 노승환
    avatar: 'assets/images/roh.PNG'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: seunghwan.roh@qraftec.com
    web: 
    twitter: 
    description: "안녕하세요"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
